### PR TITLE
Make CJamStreamer::process data parameter a reference

### PR DESCRIPTION
**Pull request by npostavs**
To avoid redundant copying.

RE: https://github.com/jamulussoftware/jamulus/pull/967#discussion_r573634373:

>  is it in any way possible for you to fork my code and raise a pull request?

Looks like it's possible :)

### CODE REVIEW

**Comment by dingodoppelt** [comment]
hi and thanks!
this is what I tried as well, but it won't compile anymore telling me:
```
src/server.cpp:420:103:   required from here
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:241:9: error: static assertion failed: Signal and slot arguments are not compatible.
```

i tried changing the other code (in server.cpp and server.h) as well but couldn't get it to work. could you please try compiling yourself to get a better idea of what is happening there?

**Comment by npostavs** [comment]
Hmm, might be my mistake. Looking at other `slots` type functions, they take `CVector` parameters by value, not by reference. So maybe it can't/shouldn't be done.

**Comment by npostavs** [comment]
Okay, I got it working. You have to match the `signal` declaration in `server.h` too. And according to this blog post, it should be passed by reference: https://embeddeduse.com/2013/06/29/copied-or-not-copied-arguments-signals-slots/ So possibly the other cases that currently pass by value are bugs.

**Comment by dingodoppelt** [comment]
thank you very much! happily merged :)

**Pull request merged**
